name: Test

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: Repository to checkout
      ref:
        required: true
        description: Ref to checkout

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # hetznercloud/tps-action

    steps:
      - if: github.event_name != 'workflow_dispatch'
        uses: actions/checkout@v5

      - if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: go env

      - uses: hetznercloud/tps-action@main

      - uses: hetznercloud/setup-hcloud@v1

      - run: hcloud server-type list
